Config:
  type: object
  properties:
    Console: 
      type: object
      properties:
        name:
          type: string
        providers:
          type: object
          additionalProperties:
            $ref: './provider.yml#/Provider'
        dependencies:
          type: object
          additionalProperties:
            type: string
        dashboards:
          type: object
          additionalProperties:
            $ref: './yaml-dashboard.yml#/YamlDashboard'
        widgets:
          type: object
          additionalProperties:
            $ref: './yaml-widget.yml#/YamlWidget'
      required:
        - name
  required:
    - Console
        
