---
openapi: 3.0.0
info:
  title: todo
  description: todo
  version: 1.0.120
paths: {}
components:
  schemas:
    Config:
      type: object
      properties:
        console:
          type: object
          properties:
            name:
              type: string
            providers:
              type: object
              additionalProperties:
                $ref: './yaml-provider.yml#/components/schemas/YamlProvider'
            dependencies:
              type: object
              additionalProperties:
                type: string
            dashboards:
              type: object
              additionalProperties:
                $ref: './yaml-dashboard.yml#/components/schemas/YamlDashboard'
            widgets:
              type: object
              additionalProperties:
                $ref: './yaml-widget.yml#/components/schemas/YamlWidget'
            
