Config:
  type: object
  properties:
    Console: 
      type: object
      properties:
        name:
          type: string
        repository:
          type: object
          properties:
            url:
              description: The github repository url to use as a source of truth for this console when hosted
              type: string
            branch:
              description: The name of the branch within the repository to use as the source of truth for this console when hosted.
              type: string
        providers:
          type: object
          additionalProperties:
            $ref: './yaml-provider.yml#/YamlProvider'
        dependencies:
          type: object
          additionalProperties:
            type: string
        dashboards:
          type: object
          additionalProperties:
            $ref: './yaml-dashboard.yml#/YamlDashboard'
        widgets:
          type: object
          additionalProperties:
            $ref: './yaml-widget.yml#/YamlWidget'
        constants:
          type: object
          additionalProperties:
            $ref: './constant.yml#/Constant'
      required:
        - name
  required:
    - Console
        
