---
openapi: 3.0.0
info:
  title: todo
  description: todo
  version: 1.0.120
paths: {}
components:
  schemas:
    Parameter:
      type: object
      properties:
        name:
          type: string
          description: a uri compliant string to name this parameter
        type:
          type: string
          description: the type for this parameter
          enum:
            - string
            - number
            - boolean
            - date
          default: string
        default:
          type: string
          description: the default value for this parameter
      required:
        - name
