---
openapi: 3.0.0
info:
  title: todo
  description: todo
  version: 1.0.120
paths: {}
components:
  schemas:
    Provider:
      type: object
      properties:
        id:
          type: string
        type: 
          type: string
          description: This describes the type of the provider
