openapi: '3.0.0'
info:
  title: API Title
  version: '1.0'
  description: Hello!
paths:
  /ping:
    $ref: ./routes/ping.yml#/ping
  /consoles:
    $ref: ./routes/console.yml#/consoles
  /consoles/{consoleName}/pages:
    $ref: ./routes/page.yml#/pages
  /consoles/{consoleName}/pages/{pageId}:
    $ref: ./routes/page.yml#/page
  /consoles/{consoleName}/widgets:
    $ref: ./routes/widget.yml#/widgets
  /consoles/{consoleName}/widgets/{widgetId}:
    $ref: ./routes/widget.yml#/widget
components:
  parameters:
    ConsoleName:
      $ref: ./parameters/path-params.yml#/ConsoleName
  schemas:
    Console:
      $ref: ./schemas/console.yml#/Console
    Widget:
      $ref: ./schemas/widget.yml#/Widget
    Page:
      $ref: ./schemas/page.yml#/Page
    TabPanel:
      $ref: ./schemas/tab-panel.yml#/TabPanel
    Tab:
      $ref: ./schemas/tab.yml#/Tab
    Provider:
      $ref: ./schemas/provider.yml#/Provider
    AwsProfileProvider:
      $ref: ./schemas/aws-profile-provider.yml#/AwsProfileProvider
    AwsKeys:
      $ref: ./schemas/aws-profile-provider.yml#/AwsKeys
    AwsAssumedRole:
      $ref: ./schemas/aws-profile-provider.yml#/AwsAssumedRole
    LocalAwsProfile:
      $ref: ./schemas/aws-profile-provider.yml#/LocalAwsProfile
    TinyStacksError:
      $ref: ./schemas/tinystacks-error.yml#/TinyStacksError
    Ping:
      $ref: ./schemas/ping.yml#/Ping
    